version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fin-tax-portal-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: fin
      POSTGRES_PASSWORD: fin_local
      POSTGRES_DB: fin_tax_portal
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
